import { AR_One_Sans } from "next/font/google";
import "./globals.css";

const ar_one_sans = AR_One_Sans({ 
  subsets: ["latin"], 
  weight: [ "400"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ar_one_sans.className}>{children}</body>
    </html>
  );
}
